from selenium import webdriver
import time
import requests
import json
import base64
from PIL import Image
import matplotlib.pyplot as plt

def zhihu_login():
    zhihu_session = requests.session()
    chrome_options = webdriver.ChromeOptions()
    chromePath = r'G:\PythonWork\ArticleSpider\chromedriver.exe'
    wd = webdriver.Chrome(executable_path=chromePath, chrome_options=chrome_options)
    loginUrl = 'https://www.zhihu.com/signin'
    while True:
        wd.get(loginUrl)
        wd.find_element_by_xpath(
            '//*[@id="root"]/div/main/div/div/div/div[2]/div[1]/form/div[1]/div[2]/div[1]/input').send_keys(
            '15972126588')
        wd.find_element_by_xpath(
            '//*[@id="root"]/div/main/div/div/div/div[2]/div[1]/form/div[2]/div/div[1]/input').send_keys('wh85864908')
        time.sleep(1)
        try:
            wd.find_element_by_css_selector('.Captcha-englishImg')
        except:
            continue
        pic = wd.find_element_by_css_selector('.Captcha-englishImg').get_attribute('src')
        with open('captcha.jpg', 'wb') as f:
            f.write(base64.b64decode(pic.replace('data:image/jpg;base64,', '')))
        img = Image.open('captcha.jpg')
        plt.figure("dog")
        plt.imshow(img)
        plt.show()
        break
    # 通过url的变化判断是否登陆成功
    captcha = input('请输入验证码：')
    wd.find_element_by_css_selector('.SignFlow-captchaContainer .Input-wrapper .Input').send_keys(captcha)
    wd.find_element_by_css_selector('.SignFlow-submitButton').click()
    while wd.current_url == loginUrl:
        pass
    cookies = wd.get_cookies()
    for cookie in cookies:
        zhihu_session.cookies.set(cookie['name'], cookie['value'])
    wd.quit()
    return zhihu_session.cookies


def zhihu_is_login(zhihu_session):
    # 判断是否登录
    inbox_url = 'https://www.zhihu.com/inbox'
    user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
    zhihu_header = {
        'User-Agent': user_agent
    }
    response = zhihu_session.get(inbox_url, headers=zhihu_header, allow_redirects=False)
    if response.status_code != 200:
        return False
    else:
        return True


def zhihu_get_captcha():
    zhihu_session = requests.session()
    user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
    zhihu_header = {
        'Connection': 'keep - alive',
        'User-Agent': user_agent
    }
    zhihu_session.get('https://www.zhihu.com/signin', headers=zhihu_header)
    zhihu_session.get('https://www.zhihu.com/api/v3/oauth/captcha?lang=en', headers=zhihu_header)
    pic = zhihu_session.put('https://www.zhihu.com/api/v3/oauth/captcha?lang=en', headers=zhihu_header)
    json_pic = json.loads(pic.content.decode())
    raw_pic = base64.b64decode(json_pic['img_base64'])
    with open('captcha.jpg', 'wb') as f:
        f.write(raw_pic)

# a = "R0lGODdhlgA8AIcAAP7+/gEBAejo6BYWFiYmJsjIyIeHh9fX12ZmZvLy8ldXV0ZGRjQ0NJaWlnd3\nd6ioqLa2tre3t6mpqTo6Op+fnyUlJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAlgA8AEAI/wABCBxI\nsKDBgwgTKlzIsKHDhxAjSpxIsaJFiAcCaNy4QIIAACBDihxJsqTJkygPBFjpAIDLlzBhCghAM4AD\nADhz6tzJs6fPn0B1BhhKQACAo0iTJn0wIEAAAgkASJ1KtarVq1ivOgjAFQKAr2DDgjUQoCwEAGjR\nGgjAtkECAHDjFhgQIACCBADy6t1rIIBfvwYSABg8WICBAIgDKEgAoPGCAJAjS4bMoEGBAw8UMAjA\n2UECAKBDix5NurTp06ADqFZNwEABAQBiy55NG4CBALgfANjNu7eCAAEQABhOfPiEAMgPAFjOvLnz\nANAnRAhAvQGA69izawfwIID3BgDCi/8fT768+fPoxwsIwB5BAgDw48ufTx++gwAGAOjfz7+/foAB\nBA4EUNDgQYMCAixkUCDAQ4gBBhAgYKBAAgAZMyZwQCDAxwACAIwkWdLkSZQpVa5k2RJAAQIBFAgA\nUNPmTZsBdA5oAMDnTwAHDCAwYABBAQEAlC5l2tTpU6hRpU6lWtXqUwMBtDIwcKDA1wcIBgQgGwBB\nAAUJAKxl29btW7hx5c6lW9fuXbx59e7l29fv3QMUGAQgXNjw4cIEEgBg3NjxY8iRJU+mHDnAZQUC\nAGwGcKABgQChRQcgcADAadSpVa9m3dp1hACxGwCgXdv27QC5CRwA0Nv37wMSIBwogCD/wHHkAR4A\nYN68uYQA0QUAoC5AwIECBwBs594dQADwAQ4AIF/e/PkCAwIEGCAAwHv48eXPp1+//oAA+QsA4C8g\nAkAFAQYSVFAAAMKEACYECOAAAMSIEgEUCBCAQAEAGjdqRBDgowMAIkeSHCkgAEoFAAwEaPkAAMyY\nMgVAWBCAgAEBAHby7OnzJ9CgQoEGKDpBAICkSpcybZrAAIEAUqcGGLDgQQIAWrdyDeA1AAIAYseS\nLdsgAFoDAdYiSADgLdy4cgEwCGCXAIC8evfy7ev3L2C+BQIQNgDgMOLEihcDELAgAOTIkiUzWBCA\nQIDMARIAQBDgcwMBAEaPhsAgAGoE/wIAsG7t2nUAAgoQGHCgAIIAALp38+7t+zfw4MKHE++NIECA\nBwCWM2/ePAD0AQYSAKhu/Tr27Nq3c+/u/Tv48OLHky9v/jz69OrXs2/vfr2AAgYQGGhgQIGBAwkA\n8O/vHyAAgQMJFjR4EGFChQwCNHT4sOEABg4KJABwEWNGjRs5dvR4kUAAkQEGDCDgoIAAACtXJmjA\nIEDMAA8A1LR5E2dOnTt59sRpIEDQBwCIFjVKFAKBAEsJHADwFGpUqVOpVqUaAGuAAwC4dvXqNcKA\nAAEGCABwFm1atWsFNEgAAG5cuQIA1LV7F29eABEC9G0AAHBgwYMBBDA8AAIAxYsZN/92/Bjy4wCT\nGQgAcBlzZswJGAQIMCABANGjCygIcPr0ggCrVxtIAAB2bNmwA9QeAMFBAN27dy+QAAB4cAEBiA8w\nIABAcuXLlQsI8DxABADTqVe3fh179uwCAnRHkABAePHiBUwIcD5ABADr1z8IEGCCAADz6dMXwCBA\nAAIA+Pf3DzCAwAAKABg8iBCAAAYBAixIAABAgIkLDggo4IDAgAEBOno0ICAkgJEkS5o8iTKlSpMH\nArh8CTMAAQUPBAC4iTPnggABEAD4CTQoAAgDAgQQACCpUgACAjhVkACA1KlUqSIIEICAgABcCQgA\nADasWLEGApgtACCt2rVs27p9C3f/rYQAdB8AuIs3r969EAL4ZVAAgGDBAgwECEDgAIDFjBcLCAAZ\nQQIAlCtbtnyAQIAACAJ4DnAAgOjRpEsDKBAgNQIArFu7fg07tuzZrhEEuA0BgO7dvHv75m0gwIQD\nAIobP478QIDlAR4AeA49enQIBAIEILAggPYHALp7/w4eQIQA5BkcAIA+vfr17Nu7f78+gPwABQDY\nv48/v34ADQL4BwhA4MACCwIEGBBAIQECBgI8VMAggIIEACxexAhhQACOAgB8DBBS5EiSJAk0AJBS\n5UqWLV2+hAkzwMwBBwDcxJlT586bBxgEABqAQAMBAIweNeogwFIHAJwmMBBA6lSq/wEICACQVetW\nrl29fgUbVuxYsmW1OggQQAEAtm3dum0QQK6CBgDs3sWbV+9evn39/gUcWPBgvQQCHBYAQPFixgIM\nVAgQ2QEAypUtX8acWfNmzp09fwYdmrMABwMCnEZ9msACBwBcv4YdW/Zs2rVt38adW/du3r19/wYe\nXPhw4sWNH0eeXPly5s2dP58dYICBAwCsX8eeXft27t29fwcfXvx48t0pBECfXn0ABwUSAIAfX/58\n+vXt38dfwEAA/v39AwwQgEGDBAAOIkyocCHDhg4fNgwgcYABCQsIDBgQYCPHAAoiAAgpciTJkiZP\nogQQYCVLlgMCwERgQMGAADZtLv9IAGAnz54+fwINKnSozwIBjhoAoHTpUgESFgSIGrUBgKpWr2LN\nqnWr1gYBvi4oAGAs2bJjBSwIoHbBAQBu38KNK3cu3bp24QbIG6AAgL5+//o9sCAAYQcADiNOrHgx\n48aMA0BeIAAA5cqWLS8IoJkAgM6eP4MOLXo06dKeBQRIjSABgNauX79OEGB2AAEAbuPOrXs37967\nFwQIDgEA8eLGjQsYECAAgQMAnkOPLv25gAgTAmAvAGA7d+4CAgRQkAAA+fLmz5tHEGA9BADu38OP\nnyAA/QEFAODPr38///7+AQIQOFBAAIMIEgBQuJAhwwAPAwgAMJEiAAEGGAwYEID/Y0eOEyAkADCS\nZMkBAVACAFAAAYMAAQgMGKDgAACbN20G0DlBAACfP4EGRRCA6AIAR5EmVbqUadOmAaAGOACAalWr\nVQsMCBAAAQCvXx0EEKsggoAEAg4YGBAgAAMBAODGlQvgQAC7AQYEGOAAQgMFCBYMCDCYQAIAhwFI\nCLCY8WIDBQBElhz5gIIAlxUA0LyZc2fPn0GHLhCAdAMAp1GnPv0gQGsCAgDEBiCAQIAADwDk1q3b\nQADfBgAEFz48QPHiBgAkV65cAIIAAQZIADA9QPXqAwYE0L6d+3YGCiAAED+efHnz59GnHx+APQEB\nAODHByAAgoIA9wNAALCfP4MA/wADMABAsKBBAA0CBBggAIDDhw4LBJg44ACAixgzXnQQoGMBAAcC\niDQAoKRJAREWBFgZYMCDBABiypxJs6bNmzhrGgjAUwGCAECDClVwAIDRowASKAgQoAGAp1CjAjgQ\noOoBAFizYg3ANUABAGDDig2bgEGAAAgADAjAtgCAt3DjvhWgIEAAAgUA6N3Lt6/fv4AD9w1AuHCA\nAQMIKCggAIDjx5AdEwhAWQCAy5gzSwgQgIAAAKBDA4gQoPQDAKhTq14doHUAAQFiI0gAoLbt27gJ\nBAgwIAGA38CDCx9OvLhx4AsCKG8AoLnz59ChC1gQIMCCAwCya8+OIIB3AQDCi/8PH6D8AAEA0qtf\nv14AgwABECAIQB8CgPv48+sHcCCAf4AOAAwkWNDgQYQJFRIUEMChgwQAJE6kWNEigwAZBzB4AAFB\nAJABJhQAUNKkyQYBVBoA0NLlS5gPAsxEEMAmAwEAdO7k2RNAgwBBFwAgWtToUaRJlS41GsBpgAMA\npE6lWtWq1AIGCAQIMIDAAAkCAIwlW3ZsALQBFABg29atWwEKAsw1EMBuAwB59e7lmzfA3wAOAAwm\nXNjwYcSJFReOEMBxAwCRJU+mXFmyAAUBCgDg3NnzZwAOAowO0ADAadSpUy8I0NpBANiwEUQQAMD2\nbdy2CzAI0LsBAODBhQ8nXtz/+HHiAZQTEADA+XPo0aUDOBAggAEA2bVrF1DgQQHwAAAEIE9+QAEA\n6dWvT28gwPsGBQLMp18/wIABAQI4aIAgAMAAAgUaAGDwIMKEChcybLjQQICIDwBQrGjxIkYABgJw\nRFCggIMAIkeSFDkgAEoBBQgEMJAAAMyYMAUQCGBTAYCcOnUG6Onzp88BDg4AKGr0KNKkSpcybRrg\nqQIBAKZSrWr1KoADCwJw7RpgAIEFDwQAACBAgoIAahUAaGsgQIABCxwoMNCAQIC8AQgIAOD3L+DA\ngAUAKGz4MOLEihczbpyYQQAAkidTrmy58oEFARYUAOD5M2jPBAKQdgDg9OkC3wgIBGjtmkEDAQBm\n065t+zbu3Lp38+7t+3dtAQECMBAA4Djy5MgFBGjOQAKA6NKnU69u/Tr27Nq3c+/uvTqCAAEeAChv\n/vz5AOoDICgA4D38+PLn069v/z7+/Pr385/PAGCAAAsAFDR40OCDAAsXFADwEGJEiRMpVrR4EWNG\njRs5UoxAIEAABAIAlDSZ4ECDBQQCtAwgAEBMmTNp1rR5E2dOnTt59vSJU0AAoUMDDAhw9CgDAwcA\nNHX6FGpUqVOpVrV6FWtWrVsFQFjgoIEBBAwAlDV7Fm1atWvZtnWLNiAAOw==\n"
# b = r"""R0lGODdhlgA8AIcAAP7+/gICAhYWFicnJ9jY2Obm5sfHx0ZGRnd3d1dXV2ZmZri4uJeXlzMzM6am
# poaGhjo6OqioqPHx8evr64uLi5ycnC0tLbi4uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAlgA8AEAI/wABCBxI
# sKDBgwgTKlzIsKHDhxAjSpxIsaLFixgzApgQoKPHAQwIAAAwIIDJCABSqlzJsqXLlRIMICAAoKbN
# mzhz6tzJs6fPn0CD7kQQoKgCAgCSKk2KQECApxEASJ1KdSqBAwECPJgAQEKCAAEOGABAtmxZAwkC
# qE1gAAAABQECDFgAoK7du3cZDAgQAEEBAIADCx5MuLDhw4gRGxAQIMCABQAiS54cecGAAAEgFADA
# uTMABwECWCAAoLRpAhACqFbdYAGA17Bjvy6AIECABABy685tYECAAAcWABhOvLjx48iTK1/OHPmB
# ANAfAJhOvbp1AAwGBAjwoAAABAICOP8goCCA+QEGAKgHQGBAgAAOAMifT59+gQEBBhgAAABCAIAB
# AhgAUNDgQYQJFS5k2NDhQ4gRJSJ8ECDAAAYANG7kCKAAAgEBAiAAUNLkSZQpVa5k2dLlS5gxZcZ0
# MCDATZw3BzwA0NPnT6BBhQ4lWtToUaRJlS5l2tTpU6AFKkAIUNXq1aoQHBQA0NXrV7BhxY4lW9bs
# WbRp1a71eiDA2wcA5M6lW9fuXbkWAgRQUEBBgAANCAAgXNjwYcMIAgQQYADAY8iRJU+mXNnyZcyZ
# KUcQECDAAQMARI8mXUFAgAAQFgBg3dr1ggYBGkQAUBsAgQQBAiAA0BuAgwYBAgh4UAD/wHHkBBQE
# CKCgAADo0aUXUBAgQAMHALRv597d+3fw4cWP5z4gwPkIANSvZ8/ewYAAAQZIAFAfAIMAARRIANAf
# AEAHAwIQLPgAAMKEChcWGBAgAAMAEiVeCGAxAYCMGjdy7OjxI8iQIkUiCGBSAQEAKleybKnSwYAA
# DQ4ICGDzgAEAOnfyXNAggAAHAIYSLUr0gYAABwYECJCAAICoUqdSrWr1KtasWrdy7er1K9UFEAIE
# gFAAANq0ateybev2Ldy4cufSrWv3Lt68evfy7ev3L+C8BhQEKGw4AAEAihczbuz4MeTIkidTrmz5
# cmMDCAQE6Oz5c2cIDgoAKG36NOrU/6pXs27t+jXs2LJjSwBg+zZuBAECDGAA4Dfw4MKHE/8dYUAA
# AQgIAGju/Dn06M0dDBCggACA7Nq3c+/u/Tv48OLHc48QIIAABAUAsG8PoICCAAEaGABg/z7+/A4E
# BBhgACCABQMCCGAAAGFChQsVVggQAIIBABMpVrRIAMGCAgA4dvT4EWRIkSNJjiQQAGWCAgBYtmxp
# QECAAA0MALB5E6fNAwECCADwE8ACAQECGABwFKkEBQGYCngAACpUBgECHCgAAGtWrVgJBPAaoAAA
# sWPJljV7Fm1atWoLDAgQ4AABAHPp1gVgQECAAAkIAPD796+FAAESTABw+DADAQEOGP8ocCBAZAgE
# AFS2fNlCgAAQJgDw/PkzAgEBAiCYAAB1atWrWbd2/Rp2bNQTEgQI0GABAN27ee9e0CBAgAMGABQv
# vqBBgAAVADR3XkBBAOkCEBAAcB179uwEDgQI8ABAePEFEAgIICACAPXr2bd3/x5+fPnz3yMIEGAA
# AwD7+ff3D7CCgAABEhgAAIBBgAACKAAAYOBAgIkJDAB4ECDAAQMAOnr8+NHAgQACKAA4aeBAgAAJ
# CAB4CTOmzJk0a9q8ifNmhAABBCAoACCo0KFEASwIEEAAAgcCDiQQECCAAAQFAFi9WgBBgAAQCgD4
# CjYsWAMNAkAgYOBAAAEMALh9Czf/rty5dOvavYvXLYEAfBMUAAA4sODBgQ0EAIAYcQEAjBs7bpwg
# QIAEACpbvmzZQIDNARoYAAA6tOjRpEubPo06terVrFujthDgwQQAtGvXXiAgQAAFBQD4/g08uPDh
# xIsbP448ufLlyhU0YECgAAAJCxQICBAAggEA3Lt7/w4+vPjx5MubP48+vfrvCxBcKCABgPz59Ovb
# v48/v/79/Pv7BwhA4ECCBQ0eRJhQ4UKGDR0+hBhR4kSKFS1exJhR40aOHT1+BBmSYYEIBwIIcABA
# 5UqWLV2+hBlT5kyaNW3exAmAAIIBAXz+BEoBwFCiRY0eRZpU6VKmTZ0+hZq0wIIE/wGsXsVqVcAD
# AgC8fgUbVuxYsmXNnkWbVu3ashQCvIUbV0AAugcIAMCbV+9evn39/gUcWPBgwoUJHwggAIEBCQAc
# OzYwIECABAQAXMacWfNmzpcVBAC9AMBo0qVNn0adWvVq1q1dvzZNIMDsBgYA3MadW/du3gAIHAgg
# AIGDAAEgLACQXPly5ssLDAgQAAIA6tWtX8eeXft27t29WydwIECAAwYAnEefHgCBAgDcv4cfH4CC
# AAEGRCCQIEAABAUAAAQgcCDBggIJJAgQAEEBAA4fQowocSLFihYvYoQYYKOACwA+gvxIIADJAQYA
# oEypUqUBAQECGAAAQEGAmgUA4P/MqRPAggEBEBgAAIBAgwABGABIqnQpUwICAgRoYAAA1apWr2LN
# qnUrV6wFFAQIMMABgLJmzS6AECDAAQMA3sKN+5aAggABFBQAAMDAgQACHgAILDiwAQgBDje4AGBx
# hAABBCAAIHky5ckEEgQIIOABgM6eP4MOLXo06dKkIQQIIIABgNauXzsYECDAAAMAbuPODYCBgAAD
# DAAIDgCBgAAHCABIDkACAwEBAgxgUAAAdeoGBgQIEAEA9+7euSMQECBAAgIAzqNPr349+/bu379/
# ECCAAAYA7uPPD2BBgwABADYgAIBgwYIEBAQIoABAw4YEBAQQwAAAAAMDAmQ8UAD/QEePHQ0ECCCA
# AQCTJ1EaOBAgwAACAGDGlDmTZk2bN3HmBIAgQE8EBQAEFToUAAUBAQIIiACAaVMABRAICKCgAACr
# VgsoCBBgwAABAQIkMACAbFmzACIMCABhAQC3b90WSBCALgUAd/Hm1buXb1+/fwHjjRCAMAIAhxEn
# RrxgQIAABwoAkDyZQIAAAhYA0LwZAIMAnz9HADCadOnSDAQECFAAQGvXAC4EkM0AQG3bt3Hn1r2b
# d2/fuCMEEJ6AAADjx5EfjxCAOQQDAKADMHAgQIAEALBjL8BgQADvAQ4QADCefHnzFQIEgLAAQPv2
# EQQECHCAAAD79/Hn17+ff3///wABCBxIsKDABQMCBEhAAIDDhxAhLhgQIIACAgAyOhgQ4AABACAd
# DAhAEsGDAQEELADAsqXLlwwEBFBAAIBNCQoCBGiwAIDPn0CDCh1KtKjRo0QJBFjagACAp1CjSl0Q
# oOoAAAAKHAggwAEAAggCiD1gAACACQoCBEgAoK3bt28nIAgQYACAuxEGBAigAIDfv4ADCx5MuLDh
# w4YNHAgQ4IABAJAjS54MYEGDAAIeFHggQICCBAICiH5QAIBp0w4GBGiwAIDr17BhKwgg4EGBAgkC
# BEhgAIDv38CDCx9OvLjx48gDKBewAIDz59CjO2cQoHqCAwcEBNiuoACA7+C/S/8YECBAAgDo06tX
# nyBAAAMIAgQQQACA/fv48+vfz7+/f4AABA4kWNDgQAIKAgQY4ADAQ4gRJUKMMCDAxYsDHADg2NEj
# RwYCAhwwAMDkSZQmCyAI0DKAAAQAZM6kWdPmTZw5de7kSROCAQBBhQ4lWtTo0aILBgQIwADAU6hR
# nxZIEMDqgwIAtG7l2tXrV7BhxY4lW9bs2a8FHgQIcIAAALhx5RIQECDAAAMA9O7l29fvX8CBBQ8m
# XNjwYcR/CygIEKCBAwCRJU+mXNnyZcyZNW/m3NnzZ8sFGgQg/QDAadSpVa9m3dr1a9ixZc+mTXvC
# gwABBgwQEEBAAOANHAAgXtwz+HHkyZUvZ97c+XPo0aUDIBBBwQAB2QMESOBgAgDw4cWPJ1/e/Hn0
# 6dWvZ9/e/Xv46QMCADs=
# """
# with open('captcha.jpg', 'wb') as f:
#     f.write(base64.b64decode(b))
zhihu_login()